clc; close all; clearvars;

% Load data
load('/home/mark/NMR Data/XmX processing/16-12-2025 acac/peakB_ao','peaks','TR_vals');

% Constants 
R1A = 1/13;
R1B = 1/13;
DR=R1A-R1B;
FLIP = deg2rad(23);    % Flip angle (radians)
skip_points = 0;       % points to omit from fitting
peak_choose = 'B';

% Acquisition times
Tacq = TR_vals(1+skip_points:end)*1e-3;  % seconds
M_0 = peaks(1+skip_points:end);          % experimental signal
err = 0.1*abs(M_0);                     % uniform noise

% Parameter bounds
lb = [0.1, 0.01, 0, 0, 1, 1];   % [kex, Pa, deltaA, deltaB, R2A,R2B]
ub = [25, 0.99, 1000, 1000, 20, 20];
Nstart = 1000;  % number of random starting points within bounds

p_scale = [10,0.5,100,100,5,5]; % kex, Pa, deltaA, deltaB, R2A, R2B

lb_s = lb./p_scale;
ub_s = ub./p_scale;

function M_abs=M_func(MA0,kex,Tacq,FLIP,DR,R1A,R1B,E1A,E1B,E2A,E2B,omega_A,omega_B,peak_choose)

    X=sqrt((kex+DR).^2-4.*MA0.*kex.*DR);
    G=X+kex+DR;
    Z=X-kex-DR;

    SS1= -(E1B.*exp((Tacq.*(Z - G + 2.*kex))./2).*(4.*X.^2.*exp(Tacq.*(G + kex + 2.*MA0.*kex))...
         + E1B.^2.*G.^2.*exp(Tacq.*(X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 ...
         + E1B.^2.*Z.^2.*exp(Tacq.*(X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 ...
         - 4.*E2B.*X.^2.*exp(Tacq.*(G + kex + MA0.*kex)).*cos(Tacq.*omega_B) ...
         + 4.*E2B.^2.*X.^2.*exp(Tacq.*(G + kex)).*cos(FLIP) + 4.*E2A.*X.^2.*exp(Tacq.*(G + 3.*MA0.*kex)).*cos(FLIP)...
         - 4.*E1B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 - 2.*E1B.*E2B.^2.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*kex))./2)...
         - 2.*E2A.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*X + 6.*MA0.*kex))./2) + E1B.^2.*E2B.^2.*G.^2.*exp(Tacq.*(X + kex)).*cos(FLIP)...
         - 4.*E1B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(2.*X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 + E1B.^2.*G.*Z.*exp(Tacq.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
         - 2.*E1B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*kex + 4.*MA0.*kex))./2).*cos(FLIP) + E1B.^2.*E2B.^2.*Z.^2.*exp(Tacq.*(X + kex)).*cos(FLIP)...
         - 2.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*kex + 4.*MA0.*kex))./2).*cos(FLIP) - 2.*E2A.*E1B.*G.*X.*exp((Tacq.*(G + 6.*MA0.*kex))./2)...
         + E1B.^2.*G.*Z.*exp(Tacq.*(2.*X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 + E2A.*E1B.^2.*E2B.^2.*G.^2.*exp(Tacq.*(X + MA0.*kex))...
         + E2A.*E1B.^2.*G.^2.*exp(Tacq.*(X + 3.*MA0.*kex)).*cos(FLIP) - 2.*E1B.*E2B.^2.*X.*Z.*exp((Tacq.*(G + 2.*kex))./2)...
         + E2A.*E1B.^2.*E2B.^2.*Z.^2.*exp(Tacq.*(X + MA0.*kex)) - 2.*E1B.*G.*X.*exp((Tacq.*(G + 2.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
         + E2A.*E1B.^2.*Z.^2.*exp(Tacq.*(X + 3.*MA0.*kex)).*cos(FLIP) - 2.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
         - 4.*E2B.*X.^2.*exp(Tacq.*(G + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         + 8.*E1B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 ...
         + 4.*E2A.*E2B.^2.*X.^2.*exp(Tacq.*(G + MA0.*kex)).*cos(FLIP).^2 ...
         + 8.*E1B.^2.*E2B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(X + kex)).*cos(FLIP)...
         - 4.*E2A.*E2B.*X.^2.*exp(Tacq.*(G + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 2.*E2A.*E1B.*G.*X.*exp((Tacq.*(G + 2.*X + 6.*MA0.*kex))./2).*cos(FLIP).^2 ...
         - 4.*E2A.*E1B.^2.*E2B.^2.*MA0.^2.*kex.^2.*exp(MA0.*Tacq.*kex)...
         - 4.*E2A.*E1B.^2.*MA0.^2.*kex.^2.*exp(3.*MA0.*Tacq.*kex).*cos(FLIP)...
         - 2.*E1B.*E2B.^2.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*kex))./2).*cos(FLIP).^2 ...
         + 8.*E2A.*E1B.^2.*E2B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(X + MA0.*kex))...
         - 4.*E1B.^2.*E2B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*kex).*cos(FLIP)...
         + 8.*E2A.*E1B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(X + 3.*MA0.*kex)).*cos(FLIP)...
         + E2A.*E1B.^2.*E2B.^2.*G.*Z.*exp(MA0.*Tacq.*kex) - 4.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 ...
         - 4.*E1B.^2.*E2B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(2.*X + kex)).*cos(FLIP) + E2A.*E1B.^2.*G.*Z.*exp(3.*MA0.*Tacq.*kex).*cos(FLIP)...
         + 2.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
         - E1B.^2.*E2B.*G.^2.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         + 4.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 + E1B.^2.*E2B.^2.*G.*Z.*exp(Tacq.*kex).*cos(FLIP)...
         - 2.*E1B.*E2B.^2.*G.*X.*exp((Tacq.*(G + 2.*kex))./2).*cos(FLIP).^2 - 2.*E2A.*E1B.*X.*Z.*exp((Tacq.*(G + 6.*MA0.*kex))./2).*cos(FLIP).^2 ...
         - E1B.^2.*E2B.*Z.^2.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - 4.*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 6.*MA0.*kex))./2)...
         + E1B.^2.*E2B.^2.*G.*Z.*exp(Tacq.*(2.*X + kex)).*cos(FLIP) + 4.*E1B.*E2B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*kex))./2)...
         + 2.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 - E2A.*E1B.^2.*E2B.*G.^2.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B)...
         - 4.*E2A.*E2B.*X.^2.*exp(Tacq.*(G + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - 4.*E2A.*E1B.^2.*E2B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(2.*X + MA0.*kex)) - 2.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
         - 4.*E2A.*E1B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(2.*X + 3.*MA0.*kex)).*cos(FLIP) - E2A.*E1B.^2.*E2B.*Z.^2.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B)...
         + 2.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 ...
         + 2.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
         + 4.*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 6.*MA0.*kex))./2) - E1B.^2.*E2B.*G.^2.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 2.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(2.*X + kex + 2.*MA0.*kex)).*cos(FLIP).^2 ...
         + E2A.*E1B.^2.*E2B.^2.*G.*Z.*exp(Tacq.*(2.*X + MA0.*kex)) + E2A.*E1B.^2.*G.*Z.*exp(Tacq.*(2.*X + 3.*MA0.*kex)).*cos(FLIP)...
         - 4.*E1B.*E2B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*kex))./2) - E1B.^2.*E2B.*Z.^2.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 2.*E1B.^2.*E2B.^2.*MA0.*Z.*kex.*exp(Tacq.*(2.*X + kex)).*cos(FLIP) + 4.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 2.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
         + 16.*E1A.*E1B.*MA0.^2.*kex.^2.*exp(Tacq.*(G + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(FLIP).^2 ...
         + 4.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP)...
         + 4.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
         + 2.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
         + 2.*E2A.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
         - E1B.^2.*E2B.*G.*Z.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ... 
         + 2.*E2A.*E1B.^2.*E2B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + MA0.*kex)) + 2.*E2A.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + 3.*MA0.*kex)).*cos(FLIP)...
         - 8.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - 2.*E2A.*E1B.^2.*E2B.^2.*MA0.*Z.*kex.*exp(Tacq.*(2.*X + MA0.*kex)) - E1B.^2.*E2B.*G.*Z.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - E2A.*E1B.^2.*E2B.*G.^2.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - 2.*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(2.*X + 3.*MA0.*kex)).*cos(FLIP)...
         + 2.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
         + 4.*E2A.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B)...
         - E2A.*E1B.^2.*E2B.*Z.^2.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - 2.*E2A.*E1B.*E2B.^2.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2).*cos(FLIP) + 2.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G...
         + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP) - 8.*E2A.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B)...
         + 4.*E2A.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B)...
         - 2.*E2A.*E1B.*E2B.^2.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2).*cos(FLIP)...
         + 4.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 2.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - E2A.*E1B.^2.*E2B.*G.*Z.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B) - 4.*E1B.^2.*E2B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + kex)).*cos(FLIP)...
         + 4.*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 6.*MA0.*kex))./2).*cos(FLIP).^2 - E2A.*E1B.^2.*E2B.*G.*Z.*exp(2.*Tacq.*(X...
         + MA0.*kex)).*cos(Tacq.*omega_B) + 4.*E1B.^2.*E2B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + kex)).*cos(FLIP)...
         + 4.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP)...
         - 8.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 4.*E1B.*E2B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*kex))./2).*cos(FLIP).^2 ...
         - E1B.^2.*E2B.*G.*Z.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 2.*E2A.*E1B.*E2B.^2.*G.*X.*exp((Tacq.*(G + 2.*MA0.*kex))./2).*cos(FLIP) ...
         + 2.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 2.*E2A.*E1B.^2.*E2B.^2.*G.*MA0.*kex.*exp(MA0.*Tacq.*kex) - 16.*E1A.*E1B.*MA0.*kex.^2.*exp(Tacq.*(G ...
         + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(FLIP).^2 - 2.*E2A.*E1B.*E2B.^2.*X.*Z.*exp((Tacq.*(G + 2.*MA0.*kex))./2).*cos(FLIP) ...
         + 2.*E2A.*E1B.^2.*G.*MA0.*kex.*exp(3.*MA0.*Tacq.*kex).*cos(FLIP) ...
         - E1B.^2.*E2B.*G.*Z.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 2.*E2A.*E1B.^2.*E2B.^2.*MA0.*Z.*kex.*exp(MA0.*Tacq.*kex) - 4.*E2A.*E1B.^2.*E2B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + MA0.*kex)) ...
         + 2.*E1B.^2.*E2B.^2.*G.*MA0.*kex.*exp(Tacq.*kex).*cos(FLIP) - 2.*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(3.*MA0.*Tacq.*kex).*cos(FLIP) ...
         - 4.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B) ...
         - 4.*E2A.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + 3.*MA0.*kex)).*cos(FLIP) ...
         - 4.*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 6.*MA0.*kex))./2).*cos(FLIP).^2 ...
         + 4.*E2A.*E1B.^2.*E2B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + MA0.*kex)) - 2.*E1B.^2.*E2B.^2.*MA0.*Z.*kex.*exp(Tacq.*kex).*cos(FLIP) ...
         + 2.*E1B.^2.*E2B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + kex)).*cos(FLIP) + 4.*E1B.*E2B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*kex))./2).*cos(FLIP).^2 ...
         + 4.*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + 3.*MA0.*kex)).*cos(FLIP) ...
         + 2.*E2A.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 2.*X + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B) ...
         + 4.*E2A.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 2.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 4.*E2A.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B) ...
         + 2.*E2A.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B) ...
         + 2.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 8.*E2A.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 4.*E2A.*E1B.^2.*E2B.*MA0.^2.*kex.^2.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 2.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 4.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 4.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - E2A.*E1B.^2.*E2B.*G.*Z.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 2.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 4.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - E2A.*E1B.^2.*E2B.*G.*Z.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 2.*E2A.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 4.*E2A.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B) ...
         - 16.*E1A.*E2A.*E1B.*E2B.^2.*MA0.*kex.^2.*exp(Tacq.*(G - kex + MA0.*kex)).*sinh((Tacq.*X)./2).^2 ...
         - 16.*E1A.*E2A.*E1B.*MA0.*kex.^2.*exp(Tacq.*(G - kex + 3.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(FLIP) ...
         - 2.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 2.*E2A.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 2.*X + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 16.*E1A.*E1B.*E2B.^2.*MA0.*kex.^2.*exp(G.*Tacq).*sinh((Tacq.*X)./2).^2.*cos(FLIP) ...
         - 4.*E2A.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B) ...
         + 2.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*(2.*X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 2.*E2A.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 2.*X + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 2.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 2.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*kex.*(MA0 + 1)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 16.*E1A.*E2A.*E1B.*E2B.^2.*MA0.^2.*kex.^2.*exp(Tacq.*(G - kex + MA0.*kex)).*sinh((Tacq.*X)./2).^2 ...
         + 4.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 16.*E1A.*E2A.*E1B.*MA0.^2.*kex.^2.*exp(Tacq.*(G - kex + 3.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(FLIP) ...
         + 2.*E2A.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 4.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*(X + kex + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 4.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 2.*E2A.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B) + 2.*E2A.*E1B.*E2B.*X.*Z.*exp((Tacq.*(G + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 2.*E2A.*E1B.*E2B.*G.*X.*exp((Tacq.*(G + 2.*X + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 16.*E1A.*E1B.*E2B.^2.*MA0.^2.*kex.^2.*exp(G.*Tacq).*sinh((Tacq.*X)./2).^2.*cos(FLIP) ...
         + 2.*E2A.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B) ...
         + 4.*E2A.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B) ...
         - 2.*E2A.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B) ...
         + 16.*E1A.*E1B.*E2B.*MA0.*kex.^2.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 4.*E2A.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         + 16.*E1A.*E1B.*E2B.*MA0.*kex.^2.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 16.*E1A.*E1B.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 2.*E2A.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 16.*E1A.*E2A.*E1B.*E2B.*MA0.*kex.^2.*exp(Tacq.*(G - kex + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B) ...
         + 2.*E2A.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(2.*MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 4.*E2A.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 2.*E2A.*E1B.^2.*E2B.*G.*MA0.*kex.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 4.*E2A.*E1B.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 4.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 4.*E2A.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(Tacq.*(X + 2.*MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         + 2.*E2A.*E1B.^2.*E2B.*MA0.*Z.*kex.*exp(2.*Tacq.*(X + MA0.*kex)).*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 16.*E1A.*E1B.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B).*cos(FLIP).^2 ...
         - 16.*E1A.*E2A.*E1B.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(G - kex + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B) ...
         + 16.*E1A.*E2A.*E1B.*E2B.*MA0.*kex.^2.*exp(Tacq.*(G - kex + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B).*cos(FLIP) ...
         - 16.*E1A.*E2A.*E1B.*E2B.*MA0.^2.*kex.^2.*exp(Tacq.*(G - kex + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).^2.*cos(Tacq.*omega_B).*cos(FLIP)))./(2.*E1A.^(1./2).*(MA0 - 1).*(E2B.^2 + exp(2.*MA0.*Tacq.*kex).*cos(FLIP) ...
         - E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B) - E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP)).*(4.*E1A.^(1./2).*X.^2.*exp(Tacq.*(G + kex)) ...
         - 2.*E1A.^(1./2).*E1B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*kex))./2) + E1A.^(1./2).*E1B.^2.*G.^2.*exp(Tacq.*(X + kex)).*cos(FLIP) ...
         + E1A.^(1./2).*E1B.^2.*Z.^2.*exp(Tacq.*(X + kex)).*cos(FLIP) + E1A.^(1./2).*E2A.*E1B.^2.*G.^2.*exp(Tacq.*(X + MA0.*kex)) ...
         + 4.*E1A.^(1./2).*E2A.*X.^2.*exp(Tacq.*(G + MA0.*kex)).*cos(FLIP) - 2.*E1A.^(1./2).*E1B.*X.*Z.*exp((Tacq.*(G + 2.*kex))./2) ...
         + E1A.^(1./2).*E2A.*E1B.^2.*Z.^2.*exp(Tacq.*(X + MA0.*kex)) - 2.*E1A.^(1./2).*E2A.*E1B.*G.*X.*exp((Tacq.*(G + 2.*MA0.*kex))./2) ...
         - 2.*E1A.^(1./2).*E1B.*G.*X.*exp((Tacq.*(G + 2.*kex))./2).*cos(FLIP) + E1A.^(1./2).*E2A.*E1B.^2.*G.*Z.*exp(MA0.*Tacq.*kex) ...
         + E1A.^(1./2).*E1B.^2.*G.*Z.*exp(Tacq.*kex).*cos(FLIP) + E1A.^(1./2).*E1B.^2.*G.*Z.*exp(Tacq.*(2.*X + kex)).*cos(FLIP) ...
         - 2.*E1A.^(1./2).*E2A.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2) + E1A.^(1./2).*E2A.*E1B.^2.*G.*Z.*exp(Tacq.*(2.*X + MA0.*kex)) ...
         - 2.*E1A.^(1./2).*E1B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*kex))./2).*cos(FLIP) + 8.*E1B.^(3./2).*MA0.*X.*kex.*exp((Tacq.*(G + Z ...
         + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) - 8.*E2A.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         + 8.*E2A.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         - 4.*E1A.^(1./2).*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2) ...
         - 4.*E2A.*E1B.^(5./2).*MA0.*Z.*kex.*exp((Tacq.*(Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         + 2.*E1A.^(1./2).*E2A.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + MA0.*kex)) ...
         - 4.*E1A.^(1./2).*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*kex))./2).*cos(FLIP) ...
         - 2.*E1A.^(1./2).*E2A.*E1B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2).*cos(FLIP) ...
         + 8.*E2A.*E1B.^(3./2).*MA0.*X.*kex.*exp((Tacq.*(G + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         + 4.*E1A.^(1./2).*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*MA0.*kex))./2) ...
         - 4.*E1B.^(5./2).*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
         + 8.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
         - 8.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
         + 4.*E1A.^(1./2).*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*kex))./2).*cos(FLIP) ...
         - 2.*E1A.^(1./2).*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + kex)).*cos(FLIP) + 2.*E1A.^(1./2).*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + kex)).*cos(FLIP) ...
         - 2.*E1A.^(1./2).*E2A.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*MA0.*kex))./2).*cos(FLIP) - 2.*E1A.^(1./2).*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(MA0.*Tacq.*kex) ...
         - 8.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
         + 8.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
         - 4.*E2A.*E1B.^(5./2).*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         - 2.*E1A.^(1./2).*E2A.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + MA0.*kex)) ...
         - 4.*E1B.^(5./2).*MA0.*Z.*kex.*exp((Tacq.*(Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
         + 8.*E2A.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         - 8.*E2A.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
         + 2.*E1A.^(1./2).*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + MA0.*kex)) - 2.*E1A.^(1./2).*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*kex).*cos(FLIP) ...
         + 2.*E1A.^(1./2).*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + kex)).*cos(FLIP)));

 switch upper(peak_choose)
    case 'A'
        My_A = -(MA0.*exp(-(Tacq.*(G - kex))./2).*sin(FLIP).*(2.*E1B.^2.*G.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 4.*MA0.*kex))./2)...
                - E1B.^3.*Z.^2.*exp((Tacq.*(Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) - 4.*E1B.*X.^2.*exp((Tacq.*(2.*G + Z + 3.*kex + 4.*MA0.*kex))./2)...
                - 4.*E1B.^2.*R1A.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 4.*MA0.*kex))./2) + 4.*E1B.^2.*R1B.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 4.*MA0.*kex))./2)...
                - E1B.^3.*E2B.^2.*G.^2.*exp((Tacq.*(4.*X + Z + 3.*kex))./2) + 4.*E1B.^2.*R1A.*X.*exp((Tacq.*(G + Z + 3.*kex + 4.*MA0.*kex))./2)...
                - 4.*E1B.^2.*R1B.*X.*exp((Tacq.*(G + Z + 3.*kex + 4.*MA0.*kex))./2) + 2.*E1B.^2.*X.*Z.*exp((Tacq.*(G + Z + 3.*kex + 4.*MA0.*kex))./2)...
                - E1B.^3.*G.^2.*exp((Tacq.*(4.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) - E1B.^3.*E2B.^2.*Z.^2.*exp((Tacq.*(Z + 3.*kex))./2)...
                + 2.*E1B.^2.*G.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) - 2.*E1B.^3.*R1A.*Z.*exp((Tacq.*(Z + 3.*kex...
                + 4.*MA0.*kex))./2).*cos(FLIP) + 2.*E1B.^3.*R1B.*Z.*exp((Tacq.*(Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                + E1B.^3.*E2B.*Z.^2.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B) + 2.*E1B.^2.*E2B.^2.*X.*Z.*exp((Tacq.*(G + Z + 3.*kex))./2)...
                + 2.*E1B.^2.*X.*Z.*exp((Tacq.*(G + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) + 4.*E1B.*E2B.*X.^2.*exp((Tacq.*(2.*G + Z + 3.*kex...
                + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B) - 2.*E1B.^3.*E2B.^2.*G.*R1A.*exp((Tacq.*(2.*X + Z + 3.*kex))./2)...
                + 2.*E1B.^3.*E2B.^2.*G.*R1A.*exp((Tacq.*(4.*X + Z + 3.*kex))./2) + 2.*E1B.^3.*E2B.^2.*G.*R1B.*exp((Tacq.*(2.*X + Z + 3.*kex))./2)...
                - 2.*E1B.^3.*E2B.^2.*G.*R1B.*exp((Tacq.*(4.*X + Z + 3.*kex))./2) - 2.*E1B.^3.*E2B.^2.*G.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex))./2)...
                + 2.*E1B.^3.*E2B.^2.*R1A.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex))./2) - 2.*E1B.^3.*E2B.^2.*R1B.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex))./2)...
                - 2.*E1B.^3.*G.*R1A.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) + 2.*E1B.^3.*G.*R1A.*exp((Tacq.*(4.*X + Z + 3.*kex...
                + 4.*MA0.*kex))./2).*cos(FLIP) + 2.*E1B.^3.*G.*R1B.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 2.*E1B.^3.*G.*R1B.*exp((Tacq.*(4.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) - 2.*E1B.^3.*G.*Z.*exp((Tacq.*(2.*X + Z...
                + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) + 2.*E1B.^3.*R1A.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 2.*E1B.^3.*R1B.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) + E1B.^3.*E2B.*G.^2.*exp((Tacq.*(4.*X...
                + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B) + 2.*E1B.^2.*E2B.^2.*G.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex))./2)...
                - 4.*E1B.*E2B.^2.*X.^2.*exp((Tacq.*(2.*G + Z + 3.*kex))./2).*cos(FLIP) - 2.*E1B.^3.*E2B.^2.*R1A.*Z.*exp((Tacq.*(Z + 3.*kex))./2)...
                + 2.*E1B.^3.*E2B.^2.*R1B.*Z.*exp((Tacq.*(Z + 3.*kex))./2) + 8.*E1B.^3.*E2B.^2.*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2)...
                - 4.*E1B.^3.*E2B.^2.*MA0.*R1A.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex))./2) - 8.*E1B.^3.*E2B.^2.*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z...
                + 3.*kex))./2) + 4.*E1B.^3.*E2B.^2.*MA0.*R1B.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex))./2)...
                + 2.*E1B.^3.*E2B.^2.*MA0.*Z.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2) - 2.*E1B.^3.*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z...
                + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP) + 2.*E1B.^3.*G.*MA0.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*G.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 8.*E1B.^3.*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 4.*E1B.^3.*MA0.*R1A.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 8.*E1B.^3.*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                + 4.*E1B.^3.*MA0.*R1B.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                + 4.*E1B.*E2B.*X.^2.*exp((Tacq.*(2.*G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^3.*MA0.*Z.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                + 4.*E1B.^2.*E2B.*R1A.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 4.*E1B.^2.*E2B.*R1B.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 2.*E1B.^3.*E2B.*R1A.*Z.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 2.*E1B.^3.*E2B.*R1B.*Z.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 4.*E1B.^3.*E2B.^2.*MA0.*R1A.*kex.*exp((Tacq.*(Z + 3.*kex))./2)...
                + 4.*E1B.^3.*E2B.^2.*MA0.*R1B.*kex.*exp((Tacq.*(Z + 3.*kex))./2)...
                - 4.*E1B.^2.*E2B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + Z + 3.*kex))./2) - 2.*E1B.^3.*E2B.^2.*MA0.*Z.*kex.*exp((Tacq.*(Z + 3.*kex))./2)...
                - 4.*E1B.^3.*MA0.*R1A.*kex.*exp((Tacq.*(Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                + 4.*E1B.^3.*MA0.*R1B.*kex.*exp((Tacq.*(Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 4.*E1B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 2.*E1B.^3.*MA0.*Z.*kex.*exp((Tacq.*(Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*R1A.*X.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 4.*E1B.^2.*E2B.*R1B.*X.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 4.*E1B.^2.*E2B.*X.*Z.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + E1B.^3.*E2B.*G.^2.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^2.*E2B.^2.*G.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex))./2).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.^2.*R1A.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex))./2).*cos(FLIP)...
                + 4.*E1B.^2.*E2B.^2.*R1B.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex))./2).*cos(FLIP)...
                + 4.*E1B.^2.*E2B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + Z + 3.*kex))./2)...
                + 4.*E1B.^2.*MA0.*X.*kex.*exp((Tacq.*(G + Z + 3.*kex + 4.*MA0.*kex))./2).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*G.*R1A.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 2.*E1B.^3.*E2B.*G.*R1A.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 2.*E1B.^3.*E2B.*G.*R1B.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 2.*E1B.^3.*E2B.*G.*R1B.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 2.*E1B.^3.*E2B.*G.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 4.*E1B.^2.*E2B.^2.*R1A.*X.*exp((Tacq.*(G + Z + 3.*kex))./2).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.^2.*R1B.*X.*exp((Tacq.*(G + Z + 3.*kex))./2).*cos(FLIP)...
                + E1B.^3.*E2B.*Z.^2.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.*R1A.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 2.*E1B.^3.*E2B.*R1B.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 2.*E1B.^2.*E2B.^2.*X.*Z.*exp((Tacq.*(G + Z + 3.*kex))./2).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.^2.*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2) + 2.*E1B.^3.*E2B.^2.*G.*MA0.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex))./2)...
                - 4.*E1B.^2.*E2B.*R1A.*X.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1B.^2.*E2B.*R1B.*X.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*X.*Z.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 2.*E1B.^3.*E2B.*G.*MA0.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 8.*E1B.^3.*E2B.*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 4.*E1B.^3.*E2B.*MA0.*R1A.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 8.*E1B.^3.*E2B.*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 4.*E1B.^3.*E2B.*MA0.*R1B.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 2.*E1B.^3.*E2B.*MA0.*Z.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*Z.*kex.*exp(Tacq.*(G + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*G.*R1A.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.*G.*R1A.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.*G.*R1B.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*G.*R1B.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*G.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1B.^3.*E2B.*MA0.*R1A.*kex.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 4.*E1B.^3.*E2B.*MA0.*R1B.*kex.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 2.*E1B.^3.*E2B.*R1A.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*R1B.*Z.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1B.^2.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.^2.*G.*kex.*exp(Tacq.*(G + X)).*sinh((Tacq.*X)./2)...
                + 2.*E1B.^3.*E2B.*MA0.*Z.*kex.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*G.*kex.*exp(Tacq.*(G + X + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).*cos(FLIP)...
                - 8.*E1A.^(3./2).*E1B.^(1./2).*X.*kex.*exp((Tacq.*(3.*G + 4.*MA0.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*G.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1B.^2.*E2B.*R1A.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*R1B.*X.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 2.*E1B.^3.*E2B.*R1A.*Z.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.*R1B.*Z.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B)...
                - 8.*E1A.^(3./2).*E1B.^(1./2).*E2B.^2.*X.*kex.*exp((3.*G.*Tacq)./2).*sinh((Tacq.*X)./2)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.^2.*Z.*kex.*exp(G.*Tacq).*sinh((Tacq.*X)./2)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*G.*MA0.*kex.*exp(Tacq.*(G + X + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).*cos(FLIP)...
                + 8.*E1A.^(3./2).*E1B.^(1./2).*MA0.*X.*kex.*exp((Tacq.*(3.*G + 4.*MA0.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP)...
                + 4.*E1B.^3.*E2B.*MA0.*R1A.*kex.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1B.^3.*E2B.*MA0.*R1B.*kex.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 8.*E1A.^(3./2).*E1B.^(1./2).*E2B.^2.*MA0.*X.*kex.*exp((3.*G.*Tacq)./2).*sinh((Tacq.*X)./2)...
                + 4.*E1B.^2.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.^2.*MA0.*Z.*kex.*exp(G.*Tacq).*sinh((Tacq.*X)./2)...
                + 2.*E1B.^3.*E2B.*MA0.*Z.*kex.*exp((Tacq.*(Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1B.^2.*E2B.*MA0.*X.*kex.*exp((Tacq.*(G + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*Z.*kex.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*MA0.*Z.*kex.*exp(Tacq.*(G + 2.*MA0.*kex)).*sinh((Tacq.*X)./2).*cos(FLIP)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*G.*kex.*exp(Tacq.*(G + X + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.^2.*G.*MA0.*kex.*exp(Tacq.*(G + X)).*sinh((Tacq.*X)./2)...
                + 2.*E1B.^3.*E2B.*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.*G.*MA0.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 8.*E1A.^(3./2).*E1B.^(1./2).*E2B.*X.*kex.*exp((Tacq.*(3.*G + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B)...
                - 8.*E1B.^3.*E2B.*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1B.^3.*E2B.*MA0.*R1A.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 8.*E1B.^3.*E2B.*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 4.*E1B.^3.*E2B.*MA0.*R1B.*kex.*exp((Tacq.*(4.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 2.*E1B.^3.*E2B.*MA0.*Z.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex + 2.*MA0.*kex))./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*G.*MA0.*kex.*exp(Tacq.*(G + X + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*Z.*kex.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 8.*E1A.^(3./2).*E1B.^(1./2).*E2B.*MA0.*X.*kex.*exp((Tacq.*(3.*G + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B)...
                - 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*G.*kex.*exp(Tacq.*(G + X + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 8.*E1A.^(3./2).*E1B.^(1./2).*E2B.*X.*kex.*exp((Tacq.*(3.*G + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*MA0.*Z.*kex.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*MA0.*Z.*kex.*exp(Tacq.*(G + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                + 4.*E1A.^(3./2).*E1B.^(3./2).*E2B.*G.*MA0.*kex.*exp(Tacq.*(G + X + MA0.*kex)).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B).*cos(FLIP)...
                - 8.*E1A.^(3./2).*E1B.^(1./2).*E2B.*MA0.*X.*kex.*exp((Tacq.*(3.*G + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2).*cos(Tacq.*omega_B).*cos(FLIP)))./(E1A.^(1./2).*(MA0...
                - 1).*(E2B.^2 + exp(2.*MA0.*Tacq.*kex).*cos(FLIP) - E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B)...
                - E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP)).*(4.*E1A.^(1./2).*X.^2.*exp(Tacq.*(G + kex))...
                - 2.*E1A.^(1./2).*E1B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*kex))./2) + E1A.^(1./2).*E1B.^2.*G.^2.*exp(Tacq.*(X + kex)).*cos(FLIP)...
                + E1A.^(1./2).*E1B.^2.*Z.^2.*exp(Tacq.*(X + kex)).*cos(FLIP) + E1A.^(1./2).*E2A.*E1B.^2.*G.^2.*exp(Tacq.*(X + MA0.*kex))...
                + 4.*E1A.^(1./2).*E2A.*X.^2.*exp(Tacq.*(G + MA0.*kex)).*cos(FLIP) - 2.*E1A.^(1./2).*E1B.*X.*Z.*exp((Tacq.*(G + 2.*kex))./2) ...
                + E1A.^(1./2).*E2A.*E1B.^2.*Z.^2.*exp(Tacq.*(X + MA0.*kex)) - 2.*E1A.^(1./2).*E2A.*E1B.*G.*X.*exp((Tacq.*(G + 2.*MA0.*kex))./2) ...
                - 2.*E1A.^(1./2).*E1B.*G.*X.*exp((Tacq.*(G + 2.*kex))./2).*cos(FLIP) + E1A.^(1./2).*E2A.*E1B.^2.*G.*Z.*exp(MA0.*Tacq.*kex) ...
                + E1A.^(1./2).*E1B.^2.*G.*Z.*exp(Tacq.*kex).*cos(FLIP) + E1A.^(1./2).*E1B.^2.*G.*Z.*exp(Tacq.*(2.*X + kex)).*cos(FLIP) ...
                - 2.*E1A.^(1./2).*E2A.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2) + E1A.^(1./2).*E2A.*E1B.^2.*G.*Z.*exp(Tacq.*(2.*X + MA0.*kex)) ...
                - 2.*E1A.^(1./2).*E1B.*X.*Z.*exp((Tacq.*(G + 2.*X + 2.*kex))./2).*cos(FLIP) ...
                + 8.*E1B.^(3./2).*MA0.*X.*kex.*exp((Tacq.*(G + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                - 8.*E2A.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                + 8.*E2A.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                - 4.*E1A.^(1./2).*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2) ...
                - 4.*E2A.*E1B.^(5./2).*MA0.*Z.*kex.*exp((Tacq.*(Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                + 2.*E1A.^(1./2).*E2A.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + MA0.*kex)) ...
                - 4.*E1A.^(1./2).*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*X + 2.*kex))./2).*cos(FLIP) ...
                - 2.*E1A.^(1./2).*E2A.*E1B.*G.*X.*exp((Tacq.*(G + 2.*X + 2.*MA0.*kex))./2).*cos(FLIP) ...
                + 8.*E2A.*E1B.^(3./2).*MA0.*X.*kex.*exp((Tacq.*(G + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                + 4.*E1A.^(1./2).*E2A.*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*MA0.*kex))./2) ...
                - 4.*E1B.^(5./2).*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                + 8.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                - 8.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                + 4.*E1A.^(1./2).*E1B.*MA0.*X.*kex.*exp((Tacq.*(G + 2.*kex))./2).*cos(FLIP) ...
                - 2.*E1A.^(1./2).*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + kex)).*cos(FLIP) ...
                + 2.*E1A.^(1./2).*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + kex)).*cos(FLIP) ...
                - 2.*E1A.^(1./2).*E2A.*E1B.*X.*Z.*exp((Tacq.*(G + 2.*MA0.*kex))./2).*cos(FLIP) ...
                - 2.*E1A.^(1./2).*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(MA0.*Tacq.*kex) ...
                - 8.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                + 8.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                - 4.*E2A.*E1B.^(5./2).*G.*MA0.*kex.*exp((Tacq.*(2.*X + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                - 2.*E1A.^(1./2).*E2A.*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(X + MA0.*kex)) ...
                - 4.*E1B.^(5./2).*MA0.*Z.*kex.*exp((Tacq.*(Z + 3.*kex))./2).*sinh((Tacq.*X)./2).*cos(FLIP) ...
                + 8.*E2A.*E1B.^(5./2).*MA0.*R1A.*kex.*exp((Tacq.*(2.*X + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                - 8.*E2A.*E1B.^(5./2).*MA0.*R1B.*kex.*exp((Tacq.*(2.*X + Z + kex + 2.*MA0.*kex))./2).*sinh((Tacq.*X)./2) ...
                + 2.*E1A.^(1./2).*E2A.*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*(X + MA0.*kex)) ...
                - 2.*E1A.^(1./2).*E1B.^2.*MA0.*Z.*kex.*exp(Tacq.*kex).*cos(FLIP) ...
                + 2.*E1A.^(1./2).*E1B.^2.*G.*MA0.*kex.*exp(Tacq.*(2.*X + kex)).*cos(FLIP)))./SS1./2;
        
        M_abs = My_A;

    case 'B'
        My_B = -(exp(MA0.*Tacq.*kex).*sin(FLIP).*(exp(MA0.*Tacq.*kex) - E2B.*cos(Tacq.*omega_B)))./(E2B.^2 + exp(2.*MA0.*Tacq.*kex).*cos(FLIP) ...
               -E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B) - E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP))./SS1./2;
        
        Mx_B = (E2B.*exp(MA0.*Tacq.*kex).*sin(Tacq.*omega_B).*sin(FLIP))./(E2B.^2 + exp(2.*MA0.*Tacq.*kex).*cos(FLIP) ...
               -E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B) - E2B.*exp(MA0.*Tacq.*kex).*cos(Tacq.*omega_B).*cos(FLIP))./SS1./2;
        
        M_abs = sqrt(My_B.^2 + Mx_B.^2);
  end

end

% Objective function with exact scale
function residuals = objective_function(params, Tacq, My_0, R1A, R1B, DR, FLIP, p_scale, peak_choose)

    params = params.*p_scale;
    kex = params(1); Pa = params(2); deltaA = params(3); deltaB = params(4); R2A = params(5); R2B = params(6);
    
    MA0 = Pa;
    nu_onres = -1./(2*Tacq);
    nu_A = -(nu_onres+deltaA);
    nu_B = -(nu_onres-deltaB);
    omega_A = 2*pi*nu_A;
    omega_B = 2*pi*nu_B;
    
    E1A = exp(-R1A*Tacq);
    E1B = exp(-R1B*Tacq);
    E2A = exp(-R2A*Tacq);
    E2B = exp(-R2B*Tacq);
    
    M_model = M_func(MA0,kex,Tacq,FLIP,DR,R1A,R1B,E1A,E1B,E2A,E2B,omega_A,omega_B,peak_choose);
    % Exact scaling for uniform noise
    scale = (M_model(:)'*My_0(:))/(M_model(:)'*M_model(:));
    residuals = scale*M_model(:) - My_0(:);
end


% lsqnonlin options 
options = optimoptions('lsqnonlin','Display','off','MaxIterations',1000,'TolFun',1e-9,'TolX',1e-9);

% Create a problem for MultiStart
x0_s = lb_s + (ub_s-lb_s)/2;  % single initial guess in middle of bounds (MultiStart will generate others)
problem = createOptimProblem('lsqnonlin', ...
    'x0', x0_s, ...
    'objective', @(p)objective_function(p,Tacq,M_0,R1A,R1B,DR,FLIP,p_scale,peak_choose), ...
    'lb', lb_s, 'ub', ub_s, ...
    'options', options);

npar = numel(lb_s);

% Generate Latin Hypercube samples in [lb,ub]
Xlhs = bsxfun(@plus,lb_s,lhsdesign(Nstart,npar).*(ub_s-lb_s));
startSet = CustomStartPointSet(Xlhs);
ms = MultiStart('Display','off');
rng default
[best_params,fval,exitflag,output,all_solutions] = run(ms, problem, Nstart);
best_params = best_params.*p_scale;

% Extract parameter matrix from all solutions
param_matrix = vertcat(all_solutions.X);  % Each row = one local minimum
fvals = [all_solutions.Fval];             % Objective (resnorm) values

% Keep only finite, successful solutions
valid_idx = isfinite(fvals);
param_matrix = param_matrix(valid_idx,:);
fvals = fvals(valid_idx);

% Plot histograms for each parameter
param_names = {'kex','Population','\Delta\nu_A','\Delta\nu_B','R_2_A','R_2_B'};

figure;
for i = 1:size(param_matrix,2)
    subplot(2,3,i)
    histogram(param_matrix(:,i),15,'FaceColor',[0.2 0.2 0.8],'EdgeColor','k');
    xlabel(param_names{i},'FontSize',12);
    ylabel('Count','FontSize',12);
    title(sprintf('%s (mean=%.3f)',param_names{i},mean(param_matrix(:,i))));
    grid on
end

% Extract optimized parameters
kex_opt = best_params(1);
pa_opt = best_params(2);
cs_A_opt = best_params(3);
cs_B_opt = best_params(4);
R2A_opt = best_params(5);
R2B_opt = best_params(6);

% Compute final fitted signal
nu_onres = -1./(2*Tacq);
nu_A = -(nu_onres+cs_A_opt);
nu_B = -(nu_onres-cs_B_opt);
omega_A = 2*pi*nu_A;
omega_B = 2*pi*nu_B;
E1A = exp(-R1A*Tacq);
E1B = exp(-R1B*Tacq);
E2A = exp(-R2A_opt*Tacq);
E2B = exp(-R2B_opt*Tacq);
MA0 = pa_opt;

M_unscaled = M_func(MA0,kex_opt,Tacq,FLIP,DR,R1A,R1B,E1A,E1B,E2A,E2B,omega_A,omega_B,peak_choose);
scale_factor = (M_unscaled(:)'*M_0(:))/(M_unscaled(:)'*M_unscaled(:));
M_opt = scale_factor*M_unscaled;

% Goodness of fit tests
residuals = M_opt - M_0;
RMSE = sqrt(mean(residuals.^2));

% Display results 
fprintf('kex = %.3f s.^-1\n', kex_opt);
fprintf('Population = %.3f\n', pa_opt);
fprintf('nu_A = %.3f Hz\n', cs_A_opt);
fprintf('nu_B = %.3f Hz\n', cs_B_opt);
fprintf('R2 = %.3f s.^-1\n', R2A_opt);
fprintf('Scale factor = %.5f\n', scale_factor);
fprintf('Final RMSE = %.5f\n\n', RMSE);

% Plot experimental and fitted data
figure
plot(Tacq*1e3, M_0, 'b-','LineWidth',2,'DisplayName','Experimental')
hold on
plot(Tacq*1e3, M_opt, 'r--','LineWidth',2,'DisplayName','Fitted')
xlabel('Tacq [ms]')
ylabel('Signal Intensity'); ylim([0,0.17])
legend
title(['Fit ',peak_choose,': kex = ' num2str(kex_opt, '%.3f') ' s^-1, Population = ' num2str(pa_opt, '%.3f') ', \Delta\nu_{A} = ' num2str(cs_A_opt, '%.3f') ' Hz,', ...
       ' \Delta\nu_{B} = ' num2str(cs_B_opt, '%.3f') ' Hz,',' R2A = ' num2str(R2A_opt, '%.3f'),' s^-1',', R2B = ' num2str(R2B_opt, '%.3f'),' s^-1'])
set(gca,'FontSize',12)

% Plot residuals 
figure
errorbar(Tacq*1e3,residuals,err,'o','MarkerSize',6,'CapSize',8,'LineWidth',1)
hold on
yline(0,'--k','LineWidth',1)
xlabel('Tacq [ms]')
ylabel('Residuals')
ylim([-0.05 0.05])
title(sprintf('RMSE = %.5f', RMSE))
set(gca,'FontSize',12)

