clc; close all; clearvars;

% Load data
load('/home/mark/NMR Data/XmX processing/Acac_NaOH/Acac_310K_KK_ao','peaks','TR_vals');

% Constants 
R1 = 1/14.2;          % Longitudinal relaxation rate (s^-1)
FLIP = deg2rad(23);    % Flip angle (radians)
skip_points = 2;       % points to omit from fitting
peak_choose = 'A';

% Acquisition times
Tacq = TR_vals(1+skip_points:end)*1e-3;  % seconds
M_0 = peaks(1+skip_points:end);          % experimental signal
err = 0.05*abs(M_0);                     % uniform noise

% Parameter bounds
lb = [0.1, 0.01, 0, 0, 0.5];   % [kex, Pa, deltaA, deltaB, R2]
ub = [15, 0.99, 1000, 1000, 15];
Nstart = 1000;  % number of random starting points within bounds


function M_abs=M_func(MA0,kex,TR,FLIP,R1,E1,E2,omegaA,omegaB,peak_choose)

switch upper(peak_choose)
    case 'A'

        My_A=-(MA0.*exp(2.*TR.*kex).*sin(FLIP).*(E1 - 1).*(E2.*exp(TR.*kex.*(MA0 - 1)).*cos(TR.*omegaA) - 1).*(exp(TR.*kex.*(2.*MA0 + 1))...
            -E1.*E2.^2 - E1.*exp(2.*MA0.*TR.*kex).*cos(FLIP) + E2.^2.*exp(TR.*kex).*cos(FLIP)...
            -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB)...
            +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
            +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
            +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            -E1.*E2.^4.*exp(TR.*kex) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^4.*MA0.*exp(2.*TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./...
            ((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB)...
            -E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(3.*TR.*kex)...
            -E1.*E2.^2.*exp(2.*MA0.*TR.*kex) + E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) - E1.*exp(2.*TR.*kex).*cos(FLIP)...
            -E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*MA0.*exp(3.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + kex + 2.*MA0.*kex))...
            -E1.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)).*(exp(4.*TR.*kex)...
            +E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)) + E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
            +E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 - E1.*exp(3.*TR.*kex).*cos(FLIP)...
            -E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1))...
            +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP)...
            +E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
            -E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3))...
            -E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
            +E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
            +E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 ...
            -E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^4.*exp(TR.*kex).*cos(FLIP)...
            -E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex)...
            -E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            +E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
            +E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex))...
            -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex))...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2))...
            -E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex) + E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex)...
            -E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            -E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex))...
            +E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
            -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP)...
            +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 ...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            -E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
            +E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));


        Mx_A=-(E2.*MA0.*exp(TR.*kex.*(MA0 + 1)).*sin(TR.*omegaA).*sin(FLIP).*(E1 - 1).*(exp(TR.*kex.*(2.*MA0 + 1))...
            -E1.*E2.^2 - E1.*exp(2.*MA0.*TR.*kex).*cos(FLIP) + E2.^2.*exp(TR.*kex).*cos(FLIP)...
            -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB)...
            +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
            +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
            +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            -E1.*E2.^4.*exp(TR.*kex) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^4.*MA0.*exp(2.*TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./...
            ((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(3.*TR.*kex) - E1.*E2.^2.*exp(2.*MA0.*TR.*kex) + E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) - E1.*exp(2.*TR.*kex).*cos(FLIP) - E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*MA0.*exp(3.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + kex + 2.*MA0.*kex)) - E1.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA) + E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)).*(exp(4.*TR.*kex) + E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)) + E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 - E1.*exp(3.*TR.*kex).*cos(FLIP) - E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)) + E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)) - E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)) - E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 - E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) - E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.^4.*exp(TR.*kex).*cos(FLIP) - E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP) - E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex) - E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 + E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex)) - E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)) - E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex) + E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex) - E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) - E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) - E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) - E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB) + E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB) - E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 + E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP) - E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP) + E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + 2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP) + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP) - E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA) + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA) - E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP) - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB) + E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) + E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA) + E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 - E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP) - E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB) - E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) + E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + 2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) - E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - 2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + 2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + 2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + 2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - 2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + 2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));


        M_abs = sqrt(My_A.^2 + Mx_A.^2);

    case 'B'

        My_B=-(exp(MA0.*TR.*kex).*sin(FLIP).*(exp(MA0.*TR.*kex)...
            -E2.*cos(TR.*omegaB)).*(E1 - 1).*(MA0 - 1).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
            +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
            +E2.^4.*exp(2.*TR.*kex).*cos(FLIP) + E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            -E1.*E2.^4.*exp(TR.*kex) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^4.*MA0.*exp(2.*TR.*kex)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP)...
            -E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(4.*TR.*kex)...
            +E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
            +E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 ...
            -E1.*exp(3.*TR.*kex).*cos(FLIP) - E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1))...
            +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
            -E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)) - E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
            +E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 ...
            -E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^4.*exp(TR.*kex).*cos(FLIP) - E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex) - E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            +E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex))...
            -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2))...
            -E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex) + E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex)...
            -E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            -E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
            -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) ...
            -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP)...
            +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 ...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            -E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
            +E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) ...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));

        Mx_B=(E2.*exp(MA0.*TR.*kex).*sin(TR.*omegaB).*sin(FLIP).*(E1 - 1).*(MA0 - 1).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
            +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
            +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) - E1.*E2.^4.*exp(TR.*kex)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^4.*MA0.*exp(2.*TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) - E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP)...
            -E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(4.*TR.*kex)...
            +E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA)...
            -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
            +E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 - E1.*exp(3.*TR.*kex).*cos(FLIP)...
            -E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1))...
            +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
            -E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)) - E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
            +E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 ...
            -E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^4.*exp(TR.*kex).*cos(FLIP) - E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex) - E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            +E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex))...
            -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)) - E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex)...
            +E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex) - E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) - E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex))...
            +E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            +E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP)...
            +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
            +E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
            +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 ...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
            +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
            +E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA)...
            +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
            -E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
            +E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) ...
            +E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
            +E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
            +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
            -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
            +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            -2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
            -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
            +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));

        M_abs = sqrt(My_B.^2 + Mx_B.^2);
end

end

% Objective function with exact scale
function residuals = objective_function(params, Tacq, My_0, R1, FLIP, peak_choose)
    
    kex = params(1); Pa = params(2); deltaA = params(3); deltaB = params(4); R2 = params(5);
    
    nu_onres = -1./(2*Tacq);
    nu_A = -(nu_onres+deltaA);
    nu_B = -(nu_onres-deltaB);
    omega_A = 2*pi*nu_A;
    omega_B = 2*pi*nu_B;
    E1 = exp(-R1*Tacq);
    E2 = exp(-R2*Tacq);
    MA0 = Pa;

    M_model = M_func(MA0,kex,Tacq,FLIP,R1,E1,E2,omega_A,omega_B,peak_choose);

    % Exact scaling for uniform noise
    scale = (M_model(:)'*My_0(:))/(M_model(:)'*M_model(:));
    residuals = scale*M_model(:) - My_0(:);
end


% lsqnonlin options 
options = optimoptions('lsqnonlin','Display','off','MaxIterations',1000,'TolFun',1e-9,'TolX',1e-9);

% Create a problem for MultiStart
x0 = lb + (ub-lb)/2;  % single initial guess in middle of bounds (MultiStart will generate others)
problem = createOptimProblem('lsqnonlin', ...
    'x0', x0, ...
    'objective', @(p)objective_function(p,Tacq,M_0,R1,FLIP,peak_choose), ...
    'lb', lb, 'ub', ub, ...
    'options', options);

% Run MultiStart 
ms = MultiStart('StartPointsToRun','bounds','Display','off');
rng default
[best_params,fval,exitflag,output,all_solutions] = run(ms, problem, Nstart);


% Extract parameter matrix from all solutions
param_matrix = vertcat(all_solutions.X);  % Each row = one local minimum
fvals = [all_solutions.Fval];             % Objective (resnorm) values

% Keep only finite, successful solutions
valid_idx = isfinite(fvals);
param_matrix = param_matrix(valid_idx,:);
fvals = fvals(valid_idx);

% Plot histograms for each parameter
param_names = {'kex','Population','\Delta\nu_A','\Delta\nu_B','R_2'};

figure;
for i = 1:size(param_matrix,2)
    subplot(2,3,i)
    histogram(param_matrix(:,i),15,'FaceColor',[0.2 0.2 0.8],'EdgeColor','k');
    xlabel(param_names{i},'FontSize',12);
    ylabel('Count','FontSize',12);
    title(sprintf('%s (mean=%.3f)',param_names{i},mean(param_matrix(:,i))));
    grid on
end

% Extract optimized parameters
kex_opt = best_params(1);
pa_opt = best_params(2);
cs_A_opt = best_params(3);
cs_B_opt = best_params(4);
R2_opt = best_params(5);

% Compute final fitted signal
nu_onres = -1./(2*Tacq);
nu_A = -(nu_onres+cs_A_opt);
nu_B = -(nu_onres-cs_B_opt);
omega_A = 2*pi*nu_A;
omega_B = 2*pi*nu_B;
E1 = exp(-R1*Tacq);
E2 = exp(-R2_opt*Tacq);
MA0 = pa_opt;

M_unscaled = M_func(MA0,kex_opt,Tacq,FLIP,R1,E1,E2,omega_A,omega_B,peak_choose);
scale_factor = (M_unscaled(:)'*M_0(:))/(M_unscaled(:)'*M_unscaled(:));
M_opt = scale_factor*M_unscaled;

residuals = M_opt - M_0;
RMSE = sqrt(mean(residuals.^2));

% Display results 
fprintf('kex = %.3f s^-1\n', kex_opt);
fprintf('Population = %.3f\n', pa_opt);
fprintf('nu_A = %.3f Hz\n', cs_A_opt);
fprintf('nu_B = %.3f Hz\n', cs_B_opt);
fprintf('R2 = %.3f s^-1\n', R2_opt);
fprintf('Scale factor = %.5f\n', scale_factor);
fprintf('Final RMSE = %.5f\n', RMSE);

% Plot experimental and fitted data
figure
plot(Tacq*1e3, M_0, 'b-','LineWidth',2,'DisplayName','Experimental')
hold on
plot(Tacq*1e3, M_opt, 'r--','LineWidth',2,'DisplayName','Fitted')
xlabel('Tacq [ms]')
ylabel('Signal Intensity'); ylim([0,0.17])
legend
title(['Fit ',peak_choose,': kex = ' num2str(kex_opt, '%.3f') ' s^-1, Population = ' num2str(pa_opt, '%.3f') ', \Delta\nu_{A} = ' num2str(cs_A_opt, '%.3f') ' Hz,', ...
       ' \Delta\nu_{B} = ' num2str(cs_B_opt, '%.3f') ' Hz,',' R2 = ' num2str(R2_opt, '%.3f'),' s^-1'])
set(gca,'FontSize',12)

% Plot residuals 
figure
errorbar(Tacq*1e3,residuals,err,'o','MarkerSize',6,'CapSize',8,'LineWidth',1)
hold on
yline(0,'--k','LineWidth',1)
xlabel('Tacq [ms]')
ylabel('Residuals')
ylim([-0.05 0.05])
title(sprintf('RMSE = %.5f', RMSE))
set(gca,'FontSize',12)

