clc; close all; clearvars;

% Load experimental data
load('/home/mark/NMR Data/XmX processing/arbitrary offset data/peak_B_FA_10_ao','peaks','TR_vals');

% Define constants (all quantities in Hz and seconds)
R1 = 1/11.54; % Longitudinal relaxation rate
FLIP = deg2rad(10); % Flip angle
skip_points = 5; % points to omit from fitting
peak_choose = 'B';

% Initial guess and bounds for [kex,Pa,delta_to_A,delta_to_B,R2] for least
% squares fit
x0 = [0.2, 0.2, 104.61, 365.9, 2]; % Initial guess: kex,Pa,delta_to_A,delta_to_B,R2
lb = [0.1, 0.01, 100.61, 363.9, 1]; % Lower bounds
ub = [6, 0.99, 106.61, 367.9, 5]; % Upper bounds

% Acquisition time range
Tacqmin = min(TR_vals(1+skip_points:end))*1e-3; Tacqmax = max(TR_vals(1+skip_points:end))*1e-3; NTacq = numel(TR_vals(1+skip_points:end)) - 1;
dTacq = (Tacqmax - Tacqmin)/NTacq;
Tacq1 = Tacqmin:dTacq:Tacqmax;

% Setting initial signal and skipping points
M_0 = peaks(1+skip_points:end);

function M_abs=M_func(MA0,kex,TR,FLIP,R1,E1,E2,omegaA,omegaB,peak_choose)

switch upper(peak_choose)
    case 'A'
        
        My_A=-(MA0.*exp(2.*TR.*kex).*sin(FLIP).*(E1 - 1).*(E2.*exp(TR.*kex.*(MA0 - 1)).*cos(TR.*omegaA) - 1).*(exp(TR.*kex.*(2.*MA0 + 1))...
             -E1.*E2.^2 - E1.*exp(2.*MA0.*TR.*kex).*cos(FLIP) + E2.^2.*exp(TR.*kex).*cos(FLIP)...
             -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB)...
             +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
             +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
             +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             -E1.*E2.^4.*exp(TR.*kex) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^4.*MA0.*exp(2.*TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./...
             ((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB)...
             -E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(3.*TR.*kex)...
             -E1.*E2.^2.*exp(2.*MA0.*TR.*kex) + E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) - E1.*exp(2.*TR.*kex).*cos(FLIP)...
             -E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*MA0.*exp(3.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + kex + 2.*MA0.*kex))...
             -E1.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)).*(exp(4.*TR.*kex)...
             +E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)) + E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
             +E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 - E1.*exp(3.*TR.*kex).*cos(FLIP)...
             -E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1))...
             +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP)...
             +E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
             -E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3))...
             -E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
             +E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
             +E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 ...
             -E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^4.*exp(TR.*kex).*cos(FLIP)...
             -E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex)...
             -E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             +E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
             +E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex))...
             -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex))...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2))...
             -E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex) + E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex)...
             -E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             -E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex))...
             +E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
             -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP)...
             +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 ...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             -E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
             +E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));


        Mx_A=-(E2.*MA0.*exp(TR.*kex.*(MA0 + 1)).*sin(TR.*omegaA).*sin(FLIP).*(E1 - 1).*(exp(TR.*kex.*(2.*MA0 + 1))...
             -E1.*E2.^2 - E1.*exp(2.*MA0.*TR.*kex).*cos(FLIP) + E2.^2.*exp(TR.*kex).*cos(FLIP)...
             -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB)...
             +E1.*E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
             +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
             +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             -E1.*E2.^4.*exp(TR.*kex) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^4.*MA0.*exp(2.*TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./...
             ((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(3.*TR.*kex) - E1.*E2.^2.*exp(2.*MA0.*TR.*kex) + E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) - E1.*exp(2.*TR.*kex).*cos(FLIP) - E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*MA0.*exp(3.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + kex + 2.*MA0.*kex)) - E1.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA) + E1.*E2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)).*(exp(4.*TR.*kex) + E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)) + E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 - E1.*exp(3.*TR.*kex).*cos(FLIP) - E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)) + E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)) - E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)) - E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 - E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) - E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.^4.*exp(TR.*kex).*cos(FLIP) - E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP) - E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex) - E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 + E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex)) - E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)) - E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex) + E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex) - E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) - E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) - E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) - E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB) + E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB) - E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 + E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP) - E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP) + E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + 2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP) + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP) - E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA) + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA) - E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP) - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB) + E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) + E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA) + E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 - E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP) - E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB) - E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) + E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP) - E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP) - E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + 2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB) + E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 - E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) - E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - 2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + 2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - 2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + 2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + 2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 - 2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) + 2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP) - E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 + E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));


        M_abs = sqrt(My_A.^2 + Mx_A.^2);

    case 'B'

        My_B=-(exp(MA0.*TR.*kex).*sin(FLIP).*(exp(MA0.*TR.*kex)...
             -E2.*cos(TR.*omegaB)).*(E1 - 1).*(MA0 - 1).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
             +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
             +E2.^4.*exp(2.*TR.*kex).*cos(FLIP) + E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             -E1.*E2.^4.*exp(TR.*kex) + E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP) + E1.*E2.^4.*MA0.*exp(2.*TR.*kex)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP) + E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 - E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP)...
             -E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(4.*TR.*kex)...
             +E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
             +E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 ...
             -E1.*exp(3.*TR.*kex).*cos(FLIP) - E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1))...
             +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
             -E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)) - E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
             +E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 ...
             -E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^4.*exp(TR.*kex).*cos(FLIP) - E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex) - E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             +E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex))...
             -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 + E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2))...
             -E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex) + E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex)...
             -E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 + E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             -E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 ...
             -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP) ...
             -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP)...
             +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 ...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             -E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
             +E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) ...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));
        
        Mx_B=(E2.*exp(MA0.*TR.*kex).*sin(TR.*omegaB).*sin(FLIP).*(E1 - 1).*(MA0 - 1).*(E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
             +exp(4.*TR.*kex).*cos(FLIP) - E1.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
             +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA) - E1.*E2.^4.*exp(TR.*kex)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^4.*MA0.*exp(2.*TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP) - E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) - E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex))...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 + E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)))./((E2.^2 + exp(2.*MA0.*TR.*kex).*cos(FLIP)...
             -E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB) - E2.*exp(MA0.*TR.*kex).*cos(TR.*omegaB).*cos(FLIP)).*(exp(4.*TR.*kex)...
             +E1.^2.*E2.^4.*exp(TR.*kex) - E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA)...
             -E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB) - E1.*E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2))...
             +E1.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 + E2.^4.*exp(2.*TR.*kex).*cos(FLIP).^2 - E1.*exp(3.*TR.*kex).*cos(FLIP)...
             -E1.*exp(4.*TR.*kex).*cos(FLIP) - E1.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1))...
             +E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP) + E2.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB) + E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             -E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP) - E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*MA0.*exp(4.*TR.*kex).*cos(FLIP) + E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1))...
             -E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)) - E1.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(FLIP).^2 ...
             +E1.^2.*MA0.^2.*exp(4.*TR.*kex).*cos(FLIP).^2 + E1.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(FLIP).^2 ...
             -E1.^3.*MA0.^2.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^4.*exp(TR.*kex).*cos(FLIP) - E1.*E2.^4.*exp(2.*TR.*kex).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(2.*TR.*kex) - E1.*E2.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             +E1.^3.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)) + E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + kex))...
             -E1.^2.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP) + E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA) + E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)) - E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)) - E1.^2.*E2.^4.*MA0.^2.*exp(TR.*kex)...
             +E1.^2.*E2.^4.*MA0.^2.*exp(2.*TR.*kex) - E1.^2.*MA0.*exp(4.*TR.*kex).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP) - E1.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP) - E1.^3.*E2.^4.*MA0.^2.*exp(TR.*(R1 + 2.*kex))...
             +E1.^3.*MA0.*exp(TR.*(R1 + 4.*kex)).*cos(FLIP).^2 - E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.*E2.^2.*MA0.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP).^2 ...
             +E1.*E2.^2.*MA0.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             +E1.^2.*E2.^2.*MA0.^2.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             -E1.^2.*E2.^4.*MA0.*exp(TR.*(R1 + 2.*kex)).*cos(FLIP)...
             +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +2.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB)...
             +E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA)...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(TR.*kex.*(2.*MA0 + 1)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(-TR.*kex.*(2.*MA0 - 3)).*cos(FLIP)...
             +E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.*E2.^3.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP).^2 ...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - 2.*MA0.*kex)).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB)...
             +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA)...
             +E1.*E2.^4.*MA0.*exp(2.*TR.*kex).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA)...
             +E1.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP).^2 ...
             -E1.^2.*E2.^2.*MA0.*exp(2.*TR.*kex.*(MA0 + 1)).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(-2.*TR.*kex.*(MA0 - 2)).*cos(FLIP)...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA)...
             +E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB)...
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 2.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP) ...
             +E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.^2.*E2.*MA0.^2.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 1)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^3.*MA0.^2.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 2)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.^3.*MA0.^2.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^2.*E2.*MA0.^2.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex + MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 2.*kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.*exp(TR.*(R1 + 3.*kex - MA0.*kex)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.^3.*E2.*MA0.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^3.*E2.*MA0.^2.*exp(TR.*(R1 + 4.*kex - MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^3.*E2.^3.*MA0.^2.*exp(TR.*(R1 + kex + MA0.*kex)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^2.*E2.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB)...
             +E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             -E1.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP).^2 ...
             +E1.^2.*E2.*MA0.*exp(TR.*kex.*(MA0 + 3)).*cos(TR.*omegaA).*cos(FLIP)...
             -E1.*E2.^3.*MA0.*exp(TR.*kex.*(MA0 + 2)).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.*E2.^3.*MA0.*exp(-TR.*kex.*(MA0 - 3)).*cos(TR.*omegaA).*cos(FLIP)...
             +E1.^2.*E2.*MA0.*exp(-TR.*kex.*(MA0 - 4)).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ... 
             +E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +2.*E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -2.*E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 2.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +E1.^3.*E2.^2.*MA0.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             -2.*E1.^3.*E2.^2.*MA0.^2.*exp(TR.*(R1 + 3.*kex)).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             +2.*E1.*E2.^2.*MA0.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP)...
             -E1.^2.*E2.^2.*MA0.^2.*exp(2.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2 ...
             +E1.^2.*E2.^2.*MA0.^2.*exp(3.*TR.*kex).*cos(TR.*omegaA).*cos(TR.*omegaB).*cos(FLIP).^2));

        M_abs = sqrt(My_B.^2 + Mx_B.^2);
end

end

% Objective function for least squares
function residuals = objective_function(params, Tacq1, My_0, R1, FLIP, peak_choose)
    kex = params(1); % Exchange rate
    Pa = params(2); % Population of on-resonance state
    delta_to_A = params(3); % Chemical shift difference
    delta_to_B = params(4);
    R2g = params(5);
    residuals = zeros(length(Tacq1), 1);
    
    Tacq=Tacq1;
    nu_onres=-1./(2*Tacq); % Chemical shift of offset
    nu_A=nu_onres+delta_to_A; % Chemical shift of peak A
    nu_B=nu_onres-delta_to_B; % Chemical shift of peak B
    
    nu_A=-nu_A;
    nu_B=-nu_B;
    omega_A=2*pi*nu_A;
    omega_B=2*pi*nu_B;
    TR=Tacq;
    E1=exp(-R1*TR);
    E2=exp(-R2g*TR);
    MA0=Pa;
    MB0=1-MA0;

    % Theoretical signal
    M_abs=M_func(MA0,kex,TR,FLIP,R1,E1,E2,omega_A,omega_B,peak_choose);

    % Normalize theoretical signal to match experimental scaling
    scale_factor=mean(My_0./M_abs);
    M_abs=M_abs*scale_factor;
    residuals=M_abs-My_0;
end


% Perform least squares optimization
options = optimoptions('lsqnonlin', 'Display', 'iter', 'MaxIterations', 1000);
[params_opt, resnorm] = lsqnonlin(@(params) objective_function(params, Tacq1, M_0, R1, FLIP, peak_choose), x0, lb, ub, options);
residuals = objective_function(params_opt, Tacq1, M_0, R1, FLIP, peak_choose);

% Extract optimized parameters
kex_opt = params_opt(1);
pa_opt = params_opt(2);
cs_A_opt = params_opt(3);
cs_B_opt = params_opt(4);
R2_opt = params_opt(5);

TR=Tacq1;
nu_onres=-1./(2*TR); % Chemical shift of offset
nu_A=nu_onres+cs_A_opt; % Chemical shift of peak A
nu_B=nu_onres-cs_B_opt; % Chemical shift of peak B

nu_A=-nu_A;
nu_B=-nu_B;
omega_A_opt=2*pi*nu_A;
omega_B_opt=2*pi*nu_B;
E1=exp(-R1*TR);
E2=exp(-R2_opt*TR);
MA0=pa_opt;
MB0=1-MA0;

% Theoretical signal
M_opt=M_func(MA0,kex_opt,TR,FLIP,R1,E1,E2,omega_A_opt,omega_B_opt,peak_choose);

% Normalize theoretical signal to match experimental scaling
scale_factor=mean(M_0./M_opt);
M_opt=M_opt*scale_factor;

% Residuals error
err = 0.05*abs(M_0);
RMSE = sqrt(resnorm/NTacq);

% Display optimized parameters
fprintf('kex_opt = %.3f s^-1\n', kex_opt);
fprintf('pa_opt = %.3f\n', pa_opt);
fprintf('cs_A_opt = %.3f Hz\n', cs_A_opt);
fprintf('cs_B_opt = %.3f Hz\n', cs_B_opt);
fprintf('R2_opt = %.3f s^-1\n', R2_opt);
fprintf('Residual norm = %.4f\n', resnorm);
fprintf('RMSE = %.4f\n', RMSE);

% Plot experimental and fitted data
figure
plot(Tacq1*1e3, M_0, 'b-', 'LineWidth', 2, 'DisplayName', 'Experimental')
hold on
plot(Tacq1*1e3, M_opt, 'r--', 'LineWidth', 2, 'DisplayName', 'Fitted')
ylabel('Signal Intensity')
xlabel('Tacq [ms]')
ylim([0,0.17])
legend
title(['Fit ',peak_choose,': kex = ' num2str(kex_opt, '%.3f') ' s^-1, Pa = ' num2str(pa_opt, '%.3f') ', \Delta\nu_{A} = ' num2str(cs_A_opt, '%.3f') ' Hz,', ...
       ' \Delta\nu_{B} = ' num2str(cs_B_opt, '%.3f') ' Hz,',' R2 = ' num2str(R2_opt, '%.3f'),' s^-1'])
ax = gca; ax.FontSize = 12;

% Residuals plot
figure
hold on
errorbar(TR*1e3,residuals,err,'o','MarkerSize',6,'CapSize',8,'LineWidth',1);
yline(0, '--k', 'LineWidth', 1);
ylabel('Residuals')
xlabel('Tacq [ms]')
ylim([-0.05,0.05])
title(['RMSE = ',num2str(RMSE)])
ax = gca; ax.FontSize = 12;


